name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 16
      uses: actions/setup-java@v4
      with:
        java-version: 16
        distribution: temurin
        overwrite-settings: false
        cache: maven
    - name: Compile Spigot version 1.16.5
      uses: SpraxDev/Action-SpigotMC@v5
      with:
        versions: 1.16.5
        remapped: true
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - uses: actions/upload-artifact@v4
      with:
        path: /home/runner/work/RealisticVillagers/RealisticVillagers/target/*.jar
